name: Test API Connectivity

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test API connectivity with curl
        run: |
          echo "Checking API connectivity..."
          curl -s -o /dev/null -w "%{http_code}" http://www.example.org/  
